# Generated by Django 2.2.5 on 2019-09-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(max_length=100),
        ),
    ]
